### ISSUE TITLE
Feature - DNS payload decoding in GUI

### ISSUE THREAD

**Issue by mattnewham** [woanware/snorbert#2]
It would be awesome if DNS packets could be decoded in the GUI, so I can determine immediately what IP was returned for a given DNS lookup. I suspect, rather than try to make this automatic, that if I could just click a button to decode DNS might be easier?

Found some perl code that will dissect a DNS packet as either pcap or straight hex with no headers. Don't know if this would be any use:

http://romana.now.ie/dnsrend/

**Comment by woanware** [comment]
This issue is closed in v1.3.0
